# Generated by Django 5.2.4 on 2025-07-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home_kitchen', 'Home & Kitchen'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('books', 'Books'), ('groceries', 'Groceries'), ('furniture', 'Furniture'), ('automotive', 'Automotive')], max_length=20),
        ),
    ]
