# Generated by Django 5.2.4 on 2025-08-04 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
